### ISSUE TITLE
React & Redux group project: set up Kanban board

### ISSUE THREAD

**Issue by Nelitaa** [Nelitaa/space-travelers-hub#66]
**Team Members:**

1.  @mperezbazan 
2.  @Nelitaa 

**Link to our GitHub project:**
[GitHub project](https://github.com/users/Nelitaa/projects/6/views/1)

![Untitled](https://user-images.githubusercontent.com/98427585/208508589-e6d9787f-f0ba-4881-ae2a-f17815acfd5c.png)

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @Nelitaa, and @mperezbazan👋, 

Your project is complete!  There is nothing else to say other than... it's time to close it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Nelitaa** [comment]
Thank you very much for review our PR!😊
